# Generated by Django 5.2.14 on 2026-05-24 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do indicador')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Indicador econômico',
                'verbose_name_plural': 'Indicadores econômicos',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do insumo')),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo unitário')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='PrecoCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_saca', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da saca')),
                ('data', models.DateField(verbose_name='Data')),
                ('mercado', models.CharField(max_length=100, verbose_name='Mercado')),
            ],
            options={
                'verbose_name': 'Preço do café',
                'verbose_name_plural': 'Preços do café',
            },
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do produtor')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Produtor',
                'verbose_name_plural': 'Produtores',
            },
        ),
        migrations.CreateModel(
            name='ProjecaoLucro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo total')),
                ('receita_estimada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Receita estimada')),
                ('lucro_estimado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Lucro estimado')),
            ],
            options={
                'verbose_name': 'Projeção de lucro',
                'verbose_name_plural': 'Projeções de lucro',
            },
        ),
        migrations.CreateModel(
            name='TipoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de custo')),
            ],
            options={
                'verbose_name': 'Tipo de custo',
                'verbose_name_plural': 'Tipos de custos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Cenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Otimista', 'Otimista'), ('Realista', 'Realista'), ('Pessimista', 'Pessimista')], max_length=20, verbose_name='Tipo de cenário')),
                ('projecao_lucro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projecaolucro', verbose_name='Projeção de lucro')),
            ],
            options={
                'verbose_name': 'Cenário',
                'verbose_name_plural': 'Cenários',
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da propriedade')),
                ('localizacao', models.CharField(max_length=200, verbose_name='Localização')),
                ('tamanho_area', models.FloatField(verbose_name='Tamanho da área')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produtor', verbose_name='Produtor')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
            },
        ),
        migrations.CreateModel(
            name='DadoClimatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(verbose_name='Temperatura')),
                ('chuva', models.FloatField(verbose_name='Quantidade de chuva')),
                ('data', models.DateField(verbose_name='Data')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Dado climático',
                'verbose_name_plural': 'Dados climáticos',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateField(verbose_name='Data de geração')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano da safra')),
                ('produtividade', models.FloatField(verbose_name='Produtividade')),
                ('area_plantada', models.FloatField(verbose_name='Área plantada')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Safra',
                'verbose_name_plural': 'Safras',
            },
        ),
        migrations.AddField(
            model_name='projecaolucro',
            name='safra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.safra', verbose_name='Safra'),
        ),
        migrations.CreateModel(
            name='Produtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_colhida', models.FloatField(verbose_name='Quantidade colhida')),
                ('area', models.FloatField(verbose_name='Área')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtividades', to='app.safra', verbose_name='Safra')),
            ],
            options={
                'verbose_name': 'Produtividade',
                'verbose_name_plural': 'Produtividades',
            },
        ),
        migrations.CreateModel(
            name='CustoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.safra', verbose_name='Safra')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipocusto', verbose_name='Tipo de custo')),
            ],
            options={
                'verbose_name': 'Custo de produção',
                'verbose_name_plural': 'Custos de produção',
            },
        ),
        migrations.CreateModel(
            name='HistoricoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('resultado', models.TextField(verbose_name='Resultado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de análise',
                'verbose_name_plural': 'Históricos de análises',
            },
        ),
    ]
